// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: grpcd/getip.proto

package grpcd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetIPServiceClient is the client API for GetIPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetIPServiceClient interface {
	GetIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*IPReply, error)
}

type getIPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetIPServiceClient(cc grpc.ClientConnInterface) GetIPServiceClient {
	return &getIPServiceClient{cc}
}

func (c *getIPServiceClient) GetIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*IPReply, error) {
	out := new(IPReply)
	err := c.cc.Invoke(ctx, "/grpcd.GetIPService/GetIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetIPServiceServer is the server API for GetIPService service.
// All implementations must embed UnimplementedGetIPServiceServer
// for forward compatibility
type GetIPServiceServer interface {
	GetIP(context.Context, *IPRequest) (*IPReply, error)
	mustEmbedUnimplementedGetIPServiceServer()
}

// UnimplementedGetIPServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetIPServiceServer struct {
}

func (UnimplementedGetIPServiceServer) GetIP(context.Context, *IPRequest) (*IPReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIP not implemented")
}
func (UnimplementedGetIPServiceServer) mustEmbedUnimplementedGetIPServiceServer() {}

// UnsafeGetIPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetIPServiceServer will
// result in compilation errors.
type UnsafeGetIPServiceServer interface {
	mustEmbedUnimplementedGetIPServiceServer()
}

func RegisterGetIPServiceServer(s grpc.ServiceRegistrar, srv GetIPServiceServer) {
	s.RegisterService(&GetIPService_ServiceDesc, srv)
}

func _GetIPService_GetIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetIPServiceServer).GetIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcd.GetIPService/GetIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetIPServiceServer).GetIP(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetIPService_ServiceDesc is the grpc.ServiceDesc for GetIPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetIPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcd.GetIPService",
	HandlerType: (*GetIPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIP",
			Handler:    _GetIPService_GetIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcd/getip.proto",
}
